### ISSUE TITLE
can it support ES 5.0+version？

### ISSUE THREAD

**Issue by mikolaje** [jprante/elasticsearch-jdbc#938] opened 2017-03-13 09:34 UTC
when I run the script it shows:
java.lang.IllegalStateException: Received message from unsupported version: [2.0.0] minimal compatible version is:
...

I'm using the lastest elasticsearch-jdbc version
thanks~

**Comment by maggu2810** [comment] 2017-03-15 08:49
Isn't that a duplicate of #915?

**Comment by jprante** [comment] 2017-03-15 09:06
Support for ES 5.x is coming soon, the coding has started but is not complete, see branch https://github.com/jprante/elasticsearch-jdbc/tree/5.0

**Closed by jprante** 2017-03-15 09:06 UTC
Labels: duplicate

**Comment by at123456** [comment] 2017-04-05 12:15
how to use the logstash fix geopoint data?
